"""mavplan — MAVLink mission planner."""
from .mission import Mission
from .waypoint import Waypoint
from .actions import (
    command_id,
    command_name,
    is_action,
    CMD_NAMES,
    NAV_WAYPOINT,
    NAV_TAKEOFF,
    NAV_LAND,
    NAV_RETURN_TO_LAUNCH,
    DO_JUMP,
    DO_CHANGE_SPEED,
    DO_SET_CAM_TRIGG_DIST,
    DO_SET_CAM_TRIGG_INTERVAL,
)
from .formats import (
    sniff_format,
    load_mission_file,
    parse_wpl,
    to_wpl,
    parse_qgc_plan,
    to_qgc_plan,
    save_qgc_plan,
)
from .pattern import (
    LawnMowerParams,
    PolygonScanParams,
    OrbitParams,
    StartCorner,
    generate_lawnmower,
    generate_polygon_scan,
    generate_orbit,
)
from .flightlog import (
    FlightLog,
    FlightStats,
    FlightPoint,
    parse_csv,
    parse_mavplan_json,
    compare_to_plan,
)
from .kml_import import (
    KmlDocument,
    KmlWaypoint,
    parse_kml,
    MissionTemplate,
    get_templates,
    save_templates_library,
    load_templates_library,
)
from .mavlink_link import (
    MAVLinkConnection,
    ConnectionInfo,
    HeartbeatInfo,
    ConnectionState,
)
from .simulate import (
    BatteryModel,
    WindModel,
    WindDirection,
    SimulationParams,
    SimulationResult,
    estimate_energy,
    insert_takeoff_landing,
    check_geofence,
    generate_report,
)
from .taskspec import (
    TaskSpec,
    Zone,
    CheckPoint,
    haversine_m,
    point_in_circle,
    segment_intersects_circle,
    point_in_polygon,
    segment_intersects_polygon,
)
from .grade import (
    Deduction,
    GradeResult,
    grade_flight,
)
from .nofly import (
    PreflightParams,
    preflight_check,
    preflight_summary,
    load_zones_from_kml,
    load_zones_json,
)
from .taskgen import (
    GeneratedTask,
    generate_task,
)
from .survey import (
    Camera,
    camera_for,
    lane_spacing_m,
    forward_spacing_m,
    altitude_for_gsd_m,
    survey_plan,
    survey_check,
    coverage_ratio,
    format_survey_check_text,
)
from .report_html import (
    render_report,
    render_survey_report,
)

__all__ = [
    "Mission",
    "Waypoint",
    "command_id",
    "command_name",
    "is_action",
    "CMD_NAMES",
    "NAV_WAYPOINT",
    "NAV_TAKEOFF",
    "NAV_LAND",
    "NAV_RETURN_TO_LAUNCH",
    "DO_JUMP",
    "DO_CHANGE_SPEED",
    "DO_SET_CAM_TRIGG_DIST",
    "DO_SET_CAM_TRIGG_INTERVAL",
    "sniff_format",
    "load_mission_file",
    "parse_wpl",
    "to_wpl",
    "parse_qgc_plan",
    "to_qgc_plan",
    "save_qgc_plan",
    "LawnMowerParams",
    "PolygonScanParams",
    "OrbitParams",
    "StartCorner",
    "generate_lawnmower",
    "generate_polygon_scan",
    "generate_orbit",
    "FlightLog",
    "FlightStats",
    "FlightPoint",
    "parse_csv",
    "parse_mavplan_json",
    "compare_to_plan",
    "KmlDocument",
    "KmlWaypoint",
    "parse_kml",
    "MissionTemplate",
    "get_templates",
    "save_templates_library",
    "load_templates_library",
    "MAVLinkConnection",
    "ConnectionInfo",
    "HeartbeatInfo",
    "ConnectionState",
    "BatteryModel",
    "WindModel",
    "WindDirection",
    "SimulationParams",
    "SimulationResult",
    "estimate_energy",
    "insert_takeoff_landing",
    "check_geofence",
    "generate_report",
    # v1.3 — teaching suite
    "TaskSpec",
    "Zone",
    "CheckPoint",
    "haversine_m",
    "point_in_circle",
    "segment_intersects_circle",
    "point_in_polygon",
    "segment_intersects_polygon",
    "Deduction",
    "GradeResult",
    "grade_flight",
    "GeneratedTask",
    "generate_task",
    "render_report",
    # v1.4 — safety preflight
    "PreflightParams",
    "preflight_check",
    "preflight_summary",
    "load_zones_from_kml",
    "load_zones_json",
    # v1.5 — survey & photogrammetry
    "Camera",
    "camera_for",
    "lane_spacing_m",
    "forward_spacing_m",
    "altitude_for_gsd_m",
    "survey_plan",
    "survey_check",
    "coverage_ratio",
    "format_survey_check_text",
    "render_survey_report",
]
__version__ = "1.5.0"
